### ISSUE TITLE
Escolher a game engine

### ISSUE THREAD

**Issue by GuilhermeFFe** [pf-game-studio/farmy#2]
Tomar a decisão sobre qual game engine utilizar
depende de #3

**Comment by GuilhermeFFe** [comment]
A [ImpactJS](https://impactjs.com/documentation/video-tutorial-create-a-game) me parece mal estruturada, mal documentada e difícil de se trabalhar.

Parece que é muito código escrito para pouco resultado.

**Comment by GuilhermeFFe** [comment]
[PhaserJS](https://phaser.io/examples/v3/view/actions/grid-align) parece não trabalhar puramente com sintaxes e funcionalidades modernas do javascript

**Comment by EduardaPS** [comment]
Foi escolhido  pixjs pois ele foi o exemplo que mais nos agradou na forma de codificar. O exemplo abaixo mostra esta forma
https://pixijs.io/examples/#/demos-basic/container.js
