### ISSUE TITLE
Definir identificador dinâmico ou fixo

### ISSUE THREAD

**Issue by GuilhermeFFe** [pf-game-studio/farmy#36]
Cada cliente terá um identificador dinâmico, aleatório, como em [Socket.IO](https://socket.io/), ou fixo? No segundo caso, haverá algum esquema interno ou externo de autenticação como [OAuth 2.0](https://oauth.net/2/)? Responder a essas perguntas antes de implementar o protocolo de sinalização no cliente - em #34 - e servidor - em #35.

**Comment by GuilhermeFFe** [comment]
Acredito que a abordagem mais simples e didática para o desenvolvimento do jogo da disciplina é um identificador fixo, com login e senha, sem esquema de autenticação externa, então essa provavelmente será a primeira abordagem utilizada.

Também penso que, dependendo da maneira com que será desenvolvido o esquema de identificação dos clientes, pode ficar bastante genérico e simples de expandir no futuro para utilizar algum `OAuth` da vida, em uma possível melhoria futura do jogo.

Em suma, minha escolha é:

* Identificador fixo;
* Sem autenticação externa, mas com implementação genérica o suficiente para permitir uma expansão sem muita fricção.

**Comment by EduardaPS** [comment]
Concordo com o identificador fixo de  login e senha e no momento sem autenticação externa. Sendo possível para futuras atualizações.
