### ISSUE TITLE
Validar registro de cliente em servidor

### ISSUE THREAD

**Issue by GuilhermeFFe** [pf-game-studio/farmy#37]
Apresentar, no corpo desta tarefa, o registro do cliente no servidor. Pode ser a captura de tela do console do Javascript com as mensagens, depuração da aplicação ou outro mecanismo válido.

Depende de #34 e de #35.

**Comment by EduardaPS** [comment]
Teste co um login registrado
![servidor](https://user-images.githubusercontent.com/42206193/124843774-0eee7200-df69-11eb-9b28-b21d7888120e.png)
![console](https://user-images.githubusercontent.com/42206193/124843781-1150cc00-df69-11eb-802b-ab7bff8a44fb.png)

**Comment by EduardaPS** [comment]
teste login não registrado
![consolenaoregistrado](https://user-images.githubusercontent.com/42206193/124843949-75739000-df69-11eb-8d80-ee2bbd8b2ce7.png)
![servidornegando](https://user-images.githubusercontent.com/42206193/124843951-786e8080-df69-11eb-8eeb-83b3dffd0473.png)

**Comment by EduardaPS** [comment]
Como é possível ver nas imagens, o servidor está funcionando de acordo com o esperado
