### ISSUE TITLE
Estudar WebRTC - revisão de redes

### ISSUE THREAD

**Issue by GuilhermeFFe** [pf-game-studio/farmy#4]
Ler o livro:

[High Performance Browse Networking](https://hpbn.co/):

Revisão de redes: capítulos 1, 2, 3, 4, 5, 6, e 7.
Opcional (para conhecimento pessoal): capítulos 8, 9, 10, 13, 14 e 16.

**Comment by GuilhermeFFe** [comment]
Feita leitura dinâmica dos capítulos, revisando as partes que não lembrava com confiança.

**Comment by EduardaPS** [comment]
leitura feita
