### ISSUE TITLE
Estudar tipos de NAT

### ISSUE THREAD

**Issue by GuilhermeFFe** [pf-game-studio/farmy#41]
Os tipos de NAT em IPv4 e outros mecanismos de ocultação de endereço em IPv4 e IPv6. A [Wikipédia em inglês](https://en.wikipedia.org/wiki/Network_address_translation) tem bom material sobre NAT.

**Comment by GuilhermeFFe** [comment]
Estudado.

**Comment by EduardaPS** [comment]
Estudado
